site_name: BEE Docs

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Documentación Técnica:
    - index.md
  - Prácticas: 
    - gpio_linux/index.md
    - pwm_linux/index.md
    - spi_linux/index.md
    - i2c_linux/index.md
    - control_servomotores/index.md
    - robotica/index.md
    - linux-kernel/config.md
    - linux-kernel/drivers.md    
    - linux-kernel/sincronizacion.md    
    - linux-kernel/interrupt-timers-pwm.md
theme:
  name: material
  features:
    - toc.integrate
