site_name: BEE Docs

nav:
  - index.md
  - Prácticas: 
    - gpio_linux/index.md
    - pwm_linux/index.md
    - spi_linux/index.md
    - i2c_linux/index.md
    - control_servomotores/index.md

theme: readthedocs
